export type GalleryPhoto = {
  id: string;
  src: string;
  alt: string;
  title: string;
  /** World X (px at identity camera) */
  x: number;
  /** World Y */
  y: number;
  /** World Z along the flight path (0…tunnel) */
  z: number;
  rotateX: number;
  rotateY: number;
  rotateZ: number;
  /** 0.7–1.3 — parallax / depth weight */
  depth: number;
  /** Card width bias vs default (0.85–1.15) */
  size: number;
};

/** Tunnel length in world units — camera loops through this range. */
export const GALLERY_TUNNEL = 2400;

/**
 * Decorative Cogniface landing photos — not user library sources.
 * Scattered in a 3D cloud so several frames stay in view during flight.
 */
export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: "g-01",
    src: "/collage/01.jpg",
    alt: "Portret w naturalnym świetle",
    title: "Światło dzienne",
    x: -180,
    y: -70,
    z: 80,
    rotateX: 5,
    rotateY: -12,
    rotateZ: -2,
    depth: 1.05,
    size: 1.08,
  },
  {
    id: "g-02",
    src: "/collage/02.jpg",
    alt: "Scena rodzinna",
    title: "Razem",
    x: 200,
    y: 40,
    z: 140,
    rotateX: -4,
    rotateY: 14,
    rotateZ: 2,
    depth: 0.95,
    size: 0.96,
  },
  {
    id: "g-03",
    src: "/collage/03.jpg",
    alt: "Krajobraz",
    title: "Horyzont",
    x: -30,
    y: 120,
    z: 320,
    rotateX: 7,
    rotateY: -5,
    rotateZ: 1,
    depth: 1.12,
    size: 1.12,
  },
  {
    id: "g-04",
    src: "/collage/04.jpg",
    alt: "Moment codzienny",
    title: "Chwila",
    x: 220,
    y: -100,
    z: 380,
    rotateX: -6,
    rotateY: 11,
    rotateZ: -3,
    depth: 0.88,
    size: 0.9,
  },
  {
    id: "g-05",
    src: "/collage/05.jpg",
    alt: "Portret z bliska",
    title: "Twarz",
    x: -240,
    y: 30,
    z: 560,
    rotateX: 3,
    rotateY: -16,
    rotateZ: 2,
    depth: 1.18,
    size: 1.05,
  },
  {
    id: "g-06",
    src: "/collage/06.jpg",
    alt: "Wnętrze",
    title: "Dom",
    x: 70,
    y: -130,
    z: 620,
    rotateX: 8,
    rotateY: 6,
    rotateZ: -1,
    depth: 1.0,
    size: 1.0,
  },
  {
    id: "g-07",
    src: "/collage/07.jpg",
    alt: "Wydarzenie",
    title: "Spotkanie",
    x: 250,
    y: 90,
    z: 800,
    rotateX: -5,
    rotateY: 13,
    rotateZ: 3,
    depth: 0.9,
    size: 0.94,
  },
  {
    id: "g-08",
    src: "/collage/08.jpg",
    alt: "Archiwalne wspomnienie",
    title: "Archiwum",
    x: -140,
    y: -40,
    z: 880,
    rotateX: 6,
    rotateY: -9,
    rotateZ: -2,
    depth: 1.08,
    size: 1.02,
  },
  // Second loop wave — same assets, offset so the tunnel feels continuous
  {
    id: "g-01b",
    src: "/collage/01.jpg",
    alt: "Portret w naturalnym świetle",
    title: "Światło dzienne",
    x: 160,
    y: 80,
    z: 1280,
    rotateX: -3,
    rotateY: 10,
    rotateZ: 2,
    depth: 1.02,
    size: 0.98,
  },
  {
    id: "g-02b",
    src: "/collage/02.jpg",
    alt: "Scena rodzinna",
    title: "Razem",
    x: -200,
    y: -90,
    z: 1340,
    rotateX: 5,
    rotateY: -13,
    rotateZ: -2,
    depth: 0.92,
    size: 1.04,
  },
  {
    id: "g-03b",
    src: "/collage/03.jpg",
    alt: "Krajobraz",
    title: "Horyzont",
    x: 40,
    y: -60,
    z: 1520,
    rotateX: -7,
    rotateY: 7,
    rotateZ: 1,
    depth: 1.1,
    size: 1.08,
  },
  {
    id: "g-04b",
    src: "/collage/04.jpg",
    alt: "Moment codzienny",
    title: "Chwila",
    x: -220,
    y: 110,
    z: 1580,
    rotateX: 4,
    rotateY: -11,
    rotateZ: 3,
    depth: 0.86,
    size: 0.92,
  },
  {
    id: "g-05b",
    src: "/collage/05.jpg",
    alt: "Portret z bliska",
    title: "Twarz",
    x: 230,
    y: -20,
    z: 1760,
    rotateX: -4,
    rotateY: 15,
    rotateZ: -1,
    depth: 1.15,
    size: 1.06,
  },
  {
    id: "g-06b",
    src: "/collage/06.jpg",
    alt: "Wnętrze",
    title: "Dom",
    x: -60,
    y: 100,
    z: 1820,
    rotateX: 6,
    rotateY: -4,
    rotateZ: 2,
    depth: 0.98,
    size: 0.97,
  },
  {
    id: "g-07b",
    src: "/collage/07.jpg",
    alt: "Wydarzenie",
    title: "Spotkanie",
    x: -250,
    y: -50,
    z: 2000,
    rotateX: -6,
    rotateY: -12,
    rotateZ: -3,
    depth: 0.94,
    size: 1.0,
  },
  {
    id: "g-08b",
    src: "/collage/08.jpg",
    alt: "Archiwalne wspomnienie",
    title: "Archiwum",
    x: 120,
    y: -110,
    z: 2100,
    rotateX: 5,
    rotateY: 8,
    rotateZ: 1,
    depth: 1.06,
    size: 1.04,
  },
];
