export type GalleryPhoto = {
  id: string;
  src: string;
  alt: string;
  title: string;
  /** World X (px at identity camera) */
  x: number;
  /** World Y */
  y: number;
  /** World Z along the flight path (0…tunnel) */
  z: number;
  rotateX: number;
  rotateY: number;
  rotateZ: number;
  /** 0.7–1.3 — parallax / depth weight */
  depth: number;
  /** Card width bias vs default (0.85–1.15) */
  size: number;
};

/** Tunnel length in world units — camera loops through this range. */
export const GALLERY_TUNNEL = 2800;

const BASE = "/landing-page-photos";

/**
 * Decorative Cogniface landing photos (from `landing-page-photos/`) —
 * not user library sources. Scattered in a 3D cloud for flight.
 */
export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: "lp-01",
    src: `${BASE}/abdullah-ali-_bIyIshKuY8-unsplash.jpg`,
    alt: "Portret w naturalnym świetle",
    title: "Światło",
    x: -180,
    y: -70,
    z: 60,
    rotateX: 5,
    rotateY: -12,
    rotateZ: -2,
    depth: 1.05,
    size: 1.08,
  },
  {
    id: "lp-02",
    src: `${BASE}/aharon-luria-8uCYBjuYk50-unsplash.jpg`,
    alt: "Scena z ludźmi",
    title: "Razem",
    x: 200,
    y: 45,
    z: 180,
    rotateX: -4,
    rotateY: 14,
    rotateZ: 2,
    depth: 0.95,
    size: 0.96,
  },
  {
    id: "lp-03",
    src: `${BASE}/aharon-luria-lefB7o-UQWE-unsplash.jpg`,
    alt: "Chwila na zdjęciu",
    title: "Chwila",
    x: -40,
    y: 120,
    z: 340,
    rotateX: 7,
    rotateY: -5,
    rotateZ: 1,
    depth: 1.12,
    size: 1.1,
  },
  {
    id: "lp-04",
    src: `${BASE}/dwayne-joe-NNXhs2VZOiA-unsplash.jpg`,
    alt: "Portret z bliska",
    title: "Twarz",
    x: 220,
    y: -95,
    z: 420,
    rotateX: -6,
    rotateY: 11,
    rotateZ: -3,
    depth: 0.88,
    size: 0.92,
  },
  {
    id: "lp-05",
    src: `${BASE}/eduard-pretsi-k-GGACCbyN8-unsplash.jpg`,
    alt: "Krajobraz i przestrzeń",
    title: "Horyzont",
    x: -240,
    y: 25,
    z: 560,
    rotateX: 3,
    rotateY: -16,
    rotateZ: 2,
    depth: 1.18,
    size: 1.06,
  },
  {
    id: "lp-06",
    src: `${BASE}/emma-swoboda-DXEhDakyt8E-unsplash.jpg`,
    alt: "Portret w miękkim świetle",
    title: "Miękko",
    x: 70,
    y: -125,
    z: 640,
    rotateX: 8,
    rotateY: 6,
    rotateZ: -1,
    depth: 1.0,
    size: 1.0,
  },
  {
    id: "lp-07",
    src: `${BASE}/hossein-gholami-4rXDdArCC8Y-unsplash.jpg`,
    alt: "Scena uliczna",
    title: "Miasto",
    x: 250,
    y: 85,
    z: 800,
    rotateX: -5,
    rotateY: 13,
    rotateZ: 3,
    depth: 0.9,
    size: 0.94,
  },
  {
    id: "lp-08",
    src: `${BASE}/hossein-gholami-_w2NEWHIGKU-unsplash.jpg`,
    alt: "Moment codzienny",
    title: "Dzień",
    x: -150,
    y: -45,
    z: 900,
    rotateX: 6,
    rotateY: -9,
    rotateZ: -2,
    depth: 1.08,
    size: 1.02,
  },
  {
    id: "lp-09",
    src: `${BASE}/jack-berry-nW4jCgctrB4-unsplash.jpg`,
    alt: "Podróż i przestrzeń",
    title: "Droga",
    x: 160,
    y: 95,
    z: 1080,
    rotateX: -3,
    rotateY: 10,
    rotateZ: 2,
    depth: 1.02,
    size: 0.98,
  },
  {
    id: "lp-10",
    src: `${BASE}/johannes-andersson-UCd78vfC8vU-unsplash.jpg`,
    alt: "Scena rodzinna",
    title: "Blisko",
    x: -210,
    y: -85,
    z: 1180,
    rotateX: 5,
    rotateY: -13,
    rotateZ: -2,
    depth: 0.92,
    size: 1.04,
  },
  {
    id: "lp-11",
    src: `${BASE}/kamil-gliwinski-xcPw1-5OHTk-unsplash.jpg`,
    alt: "Portret plenerowy",
    title: "Plener",
    x: 45,
    y: -55,
    z: 1340,
    rotateX: -7,
    rotateY: 7,
    rotateZ: 1,
    depth: 1.1,
    size: 1.08,
  },
  {
    id: "lp-12",
    src: `${BASE}/kar-ming-moo-Q_3WmguWgYg-unsplash.jpg`,
    alt: "Detal i atmosfera",
    title: "Detal",
    x: -225,
    y: 110,
    z: 1440,
    rotateX: 4,
    rotateY: -11,
    rotateZ: 3,
    depth: 0.86,
    size: 0.9,
  },
  {
    id: "lp-13",
    src: `${BASE}/mircea-solomiea-6HfHU2WoDDQ-unsplash.jpg`,
    alt: "Spotkanie i relacja",
    title: "Spotkanie",
    x: 230,
    y: -25,
    z: 1600,
    rotateX: -4,
    rotateY: 15,
    rotateZ: -1,
    depth: 1.15,
    size: 1.05,
  },
  {
    id: "lp-14",
    src: `${BASE}/mohammad-hosein-safaei-8OtGRzHpMzw-unsplash.jpg`,
    alt: "Domowa atmosfera",
    title: "Dom",
    x: -55,
    y: 105,
    z: 1720,
    rotateX: 6,
    rotateY: -4,
    rotateZ: 2,
    depth: 0.98,
    size: 0.97,
  },
  {
    id: "lp-15",
    src: `${BASE}/richard-brutyo-Sg3XwuEpybU-unsplash.jpg`,
    alt: "Archiwalne wspomnienie",
    title: "Archiwum",
    x: -255,
    y: -50,
    z: 1900,
    rotateX: -6,
    rotateY: -12,
    rotateZ: -3,
    depth: 0.94,
    size: 1.0,
  },
  {
    id: "lp-16",
    src: `${BASE}/vahid-kanani-3rgm22SpNJU-unsplash.jpg`,
    alt: "Portret w kolorze",
    title: "Kolor",
    x: 125,
    y: -110,
    z: 2040,
    rotateX: 5,
    rotateY: 8,
    rotateZ: 1,
    depth: 1.06,
    size: 1.04,
  },
  {
    id: "lp-17",
    src: `${BASE}/van-asten-maarten-DBTZ_IhbZWI-unsplash.jpg`,
    alt: "Scena z głębią",
    title: "Głębia",
    x: -90,
    y: 60,
    z: 2200,
    rotateX: -5,
    rotateY: -8,
    rotateZ: 2,
    depth: 1.0,
    size: 1.02,
  },
];
